services:
  template:
    container_name: template
    image: nginx:1.31.5-alpine
    environment:
      - ENV=dev
    ports:
      - "8080:8080"
    volumes:
      - template-data:/app/template-data
      - ./template.txt:/app/template.txt

volumes:
  template-data:
    driver: local
