apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      {{- with .Values.app.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      volumes:
        - name: {{ .Values.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: {{ .Values.configMap.name }}
          configMap:
            name: {{ .Values.configMap.name }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          {{- with .Values.app.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.app.port }}
              name: {{ .Values.app.name }}
          env:
            - name: ENV
              value: {{ .Values.app.env | quote }}
          volumeMounts:
            - name: {{ .Values.pvc.name }}
              mountPath: /tmp/data
            - name: {{ .Values.configMap.name }}
              mountPath: /app/{{ .Values.configMap.file }}
              subPath: {{ .Values.configMap.file }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
