name: Run Actionlint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  actionlint:
    permissions:
      contents: read
    uses: joeckr/ci-templates/.github/workflows/actionlint.yml@cfd448b6e12c0572704485e390efc564eb4083a9 # v1.6.0
