name: Run Commitlint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commitlint:
    permissions:
      contents: read
    uses: joeckr/ci-templates/.github/workflows/commitlint.yml@d7fc8210efc542ec3c20b118732bc0df030c7f5f # v1.5.0
