name: Gitleaks Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    permissions:
      contents: read
    uses: joeckr/ci-templates/.github/workflows/gitleaks.yml@48916bb3c57520fe2d7b179ac228b29b0d1c83cb # v1.3.0
