name: Publish Helm Chart

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@v1.1.0
    with:
      charts-dir: 'chart'
      subpath: 'charts'