name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    uses: joeckr/ci-templates/.github/workflows/semantic.yml@578d91388a3f7862fb51c4d2e685586a4d7d1daf  # v1.20.3

  matrix-build:
    needs: [release]
    if: needs.release.outputs.released == 'true' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: joeckr/ci-templates/.github/workflows/build-oci-modified.yml@578d91388a3f7862fb51c4d2e685586a4d7d1daf  # v1.20.3
    with:
      image: "oci-modified"

  helm:
    needs: [release]
    if: needs.release.outputs.released == 'true' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@578d91388a3f7862fb51c4d2e685586a4d7d1daf  # v1.20.3
    with:
      charts-dir: 'chart'
