name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    permissions:
      contents: read
    uses: joeckr/ci-templates/.github/workflows/gitleaks.yml@48916bb3c57520fe2d7b179ac228b29b0d1c83cb # v1.3.0
  zizmor:
    permissions:
      contents: read
      security-events: write # required to upload SARIF results to GitHub Advanced Security
    uses: joeckr/ci-templates/.github/workflows/zizmor.yml@c08d40f0bf0cd80de6b2f1fa2f018f944265b807 # v1.8.0
