name: Publish Helm Chart

on:
  pull_request:
    branches: [ main ]

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@v1.1.1
    with:
      charts-dir: 'chart'
      dry-run: true