name: TEST Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  matrix-build:
    uses: joeckr/ci-templates/.github/workflows/build-oci-modified.yml@v1.1.0
    with:
      image: "oci-modified"
      dry-run: true
    secrets: inherit
